#!/usr/bin/env python3
"""Bake the pen-circle tables of the tenor/ugly shell: python3 scripts/ugly/gen_tables.py [out-dir]

A circle is one loose superellipse stroke whose two ends cross. Its shape comes from a seed fixed per
ROLE (a word, a list row, a desk object), is smoothed with Catmull-Rom and stored as points relative to
the box radii (x / rx and y / ry, in 1/256), so the same box always draws the same pixels and the
firmware needs no sin or cos. The marks over the buttons (arrows, tick, the turn-back) are single pen strokes
baked the same way: a few corners, each leg broken into short steps with a seeded tremor, in 1/16 px around the
centre of the mark. Writes src/shells/ugly/UglyTables.h.
"""
import math
import random
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SEEDS = {'WORD': 11, 'OBJECT': 12, 'ROW': 13}
SUB = 3  # points per Catmull-Rom segment


def cr(pts, n):
    P = [pts[0]] + list(pts) + [pts[-1]]
    out = []
    for i in range(1, len(P) - 2):
        p0, p1, p2, p3 = P[i - 1], P[i], P[i + 1], P[i + 2]

        def tj(ti, a, b):
            return ti + max(math.hypot(b[0] - a[0], b[1] - a[1]), 1e-3) ** 0.5
        t0 = 0
        t1 = tj(t0, p0, p1)
        t2 = tj(t1, p1, p2)
        t3 = tj(t2, p2, p3)
        for k in range(n):
            t = t1 + (t2 - t1) * k / n

            def L(a, b, ta, tb):
                return tuple((tb - t) / (tb - ta) * a[j] + (t - ta) / (tb - ta) * b[j] for j in (0, 1))
            A1, A2, A3 = L(p0, p1, t0, t1), L(p1, p2, t1, t2), L(p2, p3, t2, t3)
            B1, B2 = L(A1, A2, t0, t2), L(A2, A3, t1, t3)
            out.append(L(B1, B2, t1, t2))
    out.append(pts[-1])
    return out


def circle(seed):
    r = random.Random(seed)
    a0, span, N = 200, 405, 28
    pts = []
    for i in range(N + 1):
        t = math.radians(a0 + span * i / N)
        g = 1 + 0.07 * i / N + r.uniform(-0.025, 0.025)
        c, s = math.cos(t), math.sin(t)
        e = 0.8
        pts.append((math.copysign(abs(c) ** e, c) * g, math.copysign(abs(s) ** e, s) * g))
    return [(round(x * 256), round(y * 256)) for x, y in cr(pts, SUB)]


def pen(path, seed):
    """One pen stroke: ('ln', corners) keeps its corners, ('cr', points) is smoothed. Legs are cut into ~3 px steps
    and every point shakes by up to half a pixel; the corners shake less, so a tip stays a tip."""
    r = random.Random(seed)
    pts = []
    for kind, corners in path:
        if kind == 'cr':
            pts += [(x, y, 0.45) for x, y in cr(corners, 3)]
            continue
        for a, b in zip(corners, corners[1:]):
            n = max(1, round(math.hypot(b[0] - a[0], b[1] - a[1]) / 3))
            for i in range(n):
                pts.append((a[0] + (b[0] - a[0]) * i / n, a[1] + (b[1] - a[1]) * i / n, 0.45 if i else 0.3))
        pts.append((corners[-1][0], corners[-1][1], 0.3))
    return [(round((x + r.uniform(-j, j)) * 16), round((y + r.uniform(-j, j)) * 16)) for x, y, j in pts]


def arrow(tail, tip, wing_a, wing_b):
    """Shaft, point, one wing, back to the point, the other wing: the way a hand draws an arrow."""
    return [('ln', [tail, tip, wing_a, tip, wing_b])]


# Marks over the buttons, y down, centred on (0, 0), about 20 px across.
MARKS = {
    'LEFT': arrow((10, 1), (-10, 0), (-3, -8), (-3, 8)),
    'RIGHT': arrow((-10, 1), (10, 0), (3, -8), (3, 8)),
    'UP': arrow((1, 10), (0, -10), (-8, -3), (8, -3)),
    'DOWN': arrow((-1, -10), (0, 10), (-8, 3), (8, 3)),
    'TICK': [('ln', [(-9, -1), (-3, 7), (10, -10)])],
    # back: up the right side, over to the left, and the point with its wings
    'BACK': [('cr', [(9, 8), (11, 0), (7, -6), (0, -8), (-9, -6)]), ('ln', [(-9, -6), (-3, -12), (-9, -6), (-3, -1)])],
}


def main(out=None):
    o = ['// Generated by scripts/ugly/gen_tables.py. Do not edit by hand.',
         '#pragma once', '#include <cstdint>', '', 'namespace ugly {', '',
         '// Pen circles: points as x / rx and y / ry in 1/256, drawn from the first to the last.',
         'struct CirclePoint {', '  int16_t x, y;', '};', '']
    for name, seed in SEEDS.items():
        pts = circle(seed)
        o.append('inline constexpr CirclePoint CIRCLE_%s[] = {' % name)
        for i in range(0, len(pts), 6):
            o.append('    ' + ' '.join('{%d, %d},' % p for p in pts[i:i + 6]))
        o += ['};', 'inline constexpr int CIRCLE_%s_COUNT = %d;' % (name, len(pts)), '']
    o += ['// Marks over the buttons: pen points in 1/16 px around the centre of the mark, drawn from the first to the last.']
    for i, (name, path) in enumerate(MARKS.items()):
        pts = pen(path, 21 + i)
        o.append('inline constexpr CirclePoint MARK_%s[] = {' % name)
        for k in range(0, len(pts), 6):
            o.append('    ' + ' '.join('{%d, %d},' % p for p in pts[k:k + 6]))
        o += ['};', 'inline constexpr int MARK_%s_COUNT = %d;' % (name, len(pts)), '']
    o += ['}  // namespace ugly', '']
    (Path(out) if out else ROOT / 'src/shells/ugly').joinpath('UglyTables.h').write_text('\n'.join(o))
    print('ok')


if __name__ == '__main__':
    import sys
    main(sys.argv[1] if len(sys.argv) > 1 else None)
