#!/usr/bin/env python3
"""Bake the pen-circle tables of the tenor/ugly shell: python3 scripts/ugly/gen_tables.py [out-dir]

A circle is one loose superellipse stroke whose two ends cross. Its shape comes from a seed fixed per
ROLE (a word, a list row, a desk object), is smoothed with Catmull-Rom and stored as points relative to
the box radii (x / rx and y / ry, in 1/256), so the same box always draws the same pixels and the
firmware needs no sin or cos. Writes src/shells/ugly/UglyTables.h.
"""
import math
import random
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SEEDS = {'WORD': 11, 'OBJECT': 12, 'ROW': 13}
SUB = 3  # points per Catmull-Rom segment


def cr(pts, n):
    P = [pts[0]] + list(pts) + [pts[-1]]
    out = []
    for i in range(1, len(P) - 2):
        p0, p1, p2, p3 = P[i - 1], P[i], P[i + 1], P[i + 2]

        def tj(ti, a, b):
            return ti + max(math.hypot(b[0] - a[0], b[1] - a[1]), 1e-3) ** 0.5
        t0 = 0
        t1 = tj(t0, p0, p1)
        t2 = tj(t1, p1, p2)
        t3 = tj(t2, p2, p3)
        for k in range(n):
            t = t1 + (t2 - t1) * k / n

            def L(a, b, ta, tb):
                return tuple((tb - t) / (tb - ta) * a[j] + (t - ta) / (tb - ta) * b[j] for j in (0, 1))
            A1, A2, A3 = L(p0, p1, t0, t1), L(p1, p2, t1, t2), L(p2, p3, t2, t3)
            B1, B2 = L(A1, A2, t0, t2), L(A2, A3, t1, t3)
            out.append(L(B1, B2, t1, t2))
    out.append(pts[-1])
    return out


def circle(seed):
    r = random.Random(seed)
    a0, span, N = 200, 405, 28
    pts = []
    for i in range(N + 1):
        t = math.radians(a0 + span * i / N)
        g = 1 + 0.07 * i / N + r.uniform(-0.025, 0.025)
        c, s = math.cos(t), math.sin(t)
        e = 0.8
        pts.append((math.copysign(abs(c) ** e, c) * g, math.copysign(abs(s) ** e, s) * g))
    return [(round(x * 256), round(y * 256)) for x, y in cr(pts, SUB)]


def main(out=None):
    o = ['// Generated by scripts/ugly/gen_tables.py. Do not edit by hand.',
         '#pragma once', '#include <cstdint>', '', 'namespace ugly {', '',
         '// Pen circles: points as x / rx and y / ry in 1/256, drawn from the first to the last.',
         'struct CirclePoint {', '  int16_t x, y;', '};', '']
    for name, seed in SEEDS.items():
        pts = circle(seed)
        o.append('inline constexpr CirclePoint CIRCLE_%s[] = {' % name)
        for i in range(0, len(pts), 6):
            o.append('    ' + ' '.join('{%d, %d},' % p for p in pts[i:i + 6]))
        o += ['};', 'inline constexpr int CIRCLE_%s_COUNT = %d;' % (name, len(pts)), '']
    o += ['}  // namespace ugly', '']
    (Path(out) if out else ROOT / 'src/shells/ugly').joinpath('UglyTables.h').write_text('\n'.join(o))
    print('ok')


if __name__ == '__main__':
    import sys
    main(sys.argv[1] if len(sys.argv) > 1 else None)
