#!/usr/bin/env python3
"""Bake the Mansalva handwriting font used by the tenor/ugly shell.

python3 scripts/ugly/gen_font.py [out-dir]   (default src/shells/ugly/fonts, files ugly_<px>.h)

The letters are baked straight: nominal size, no turn, on the baseline, with the advance of the font.
The mode "ugly af" of the shell turns, shrinks and lifts them while it draws (UglyLogic.h, warpOf);
the mode "ugly" draws them as they are. The result is a 1-bit EpdFontData with no kerning and no
compression, so the stock renderer draws it like the built-in UI fonts. Pure Python (PIL, numpy),
deterministic.
"""
import sys
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / 'lib/EpdFont/builtinFonts/source/Mansalva/Mansalva-Regular.ttf'
OUT = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / 'src/shells/ugly/fonts'

FULL = (list(range(0x20, 0x7F)) + list(range(0xC0, 0x100)) + [0xD7 - 0xD7 + 0x102, 0x103, 0x110, 0x111, 0x128, 0x129,
        0x168, 0x169, 0x1A0, 0x1A1, 0x1AF, 0x1B0] + list(range(0x1EA0, 0x1EFA)) +
        [0x2018, 0x2019, 0x201C, 0x201D, 0x2026])
FULL = sorted(set(FULL) - {0xD7, 0xF7})
# Page titles are the few words of the five Home pages (Vietnamese and English) plus digits, and the title of the diary.
TITLE_TEXT = ('Gần đây Thư mục Yêu thích Thống kê Cài đặt File Recent Folder Favorites Stats Settings '
              'Gửi Giao diện Hiển thị Đọc Điều khiển Hệ thống Thiết bị Khác Bàn phím Ngủ Cử chỉ Sách Mở 0123456789/ '
              'Nhật ký Diary')
TITLE = sorted({ord(c) for c in TITLE_TEXT})
SIZES = {22: FULL, 30: FULL, 38: FULL, 52: TITLE}
ADVANCE_Y = {22: 30, 30: 40, 38: 50, 52: 68}


def variant(ch, px):
    """(mask, advance, dy, canvas, font advance) of one character at its nominal size, straight."""
    ft = ImageFont.truetype(str(SRC), px)
    w = int(px * 3) + 8
    im = Image.new('L', (w, w), 0)
    ImageDraw.Draw(im).text((w // 2, w // 2), ch, font=ft, fill=255, anchor='ms')
    fadv = ft.getlength(ch)
    return np.array(im) >= 128, fadv, 0, w, fadv


def bake(px, cps):
    bitmap, glyphs = bytearray(), []
    for cp in cps:
        if cp == 0x20:
            glyphs.append((0, 0, round(px * 0.30 * 16), 0, 0, 0, len(bitmap)))
            continue
        mask, adv, dy, w, fadv = variant(chr(cp), px)
        ys, xs = np.nonzero(mask)
        sub = mask[ys.min():ys.max() + 1, xs.min():xs.max() + 1]
        packed = np.packbits(sub.reshape(-1)).tobytes()
        left = int(xs.min()) + int(round(fadv / 2 - w // 2))
        top = -(int(ys.min()) + int(round(dy - w // 2)))
        glyphs.append((sub.shape[1], sub.shape[0], round(adv * 16), left, top, len(packed), len(bitmap)))
        bitmap += packed
    return bytes(bitmap), glyphs


def emit(px, cps):
    bitmap, glyphs = bake(px, cps)
    name = 'ugly_%d' % px
    runs, start = [], 0
    for i in range(1, len(cps) + 1):
        if i == len(cps) or cps[i] != cps[i - 1] + 1:
            runs.append((cps[start], cps[i - 1], start))
            start = i
    asc = max(g[4] for g in glyphs)
    desc = min(g[4] - g[1] for g in glyphs)
    o = ['// Generated by scripts/ugly/gen_font.py from Mansalva-Regular.ttf (SIL OFL 1.1). Do not edit by hand.',
         '#pragma once', '#include <EpdFontData.h>', '',
         'static const uint8_t %sBitmaps[%d] = {' % (name, len(bitmap))]
    for i in range(0, len(bitmap), 16):
        o.append('    ' + ', '.join('0x%02X' % b for b in bitmap[i:i + 16]) + ',')
    o += ['};', '', 'static const EpdGlyph %sGlyphs[] = {' % name]
    o += ['    {%d, %d, %d, %d, %d, %d, %d},' % g for g in glyphs]
    o += ['};', '', 'static const EpdUnicodeInterval %sIntervals[] = {' % name]
    o += ['    {0x%X, 0x%X, %d},' % r for r in runs]
    o += ['};', '', 'static const EpdFontData %s = {' % name,
          '    %sBitmaps, %sGlyphs, %sIntervals, %d, %d, %d, %d, false,' % (name, name, name, len(runs), ADVANCE_Y[px], asc, desc),
          '    nullptr, 0, nullptr,  // not compressed',
          '    nullptr, nullptr, nullptr, nullptr, nullptr, nullptr,  // no kerning classes',
          '    nullptr, nullptr, nullptr, nullptr,  // no kerning matrix',
          '    0, 0, 0, 0, nullptr, 0,',
          '};', '']
    (OUT / (name + '.h')).write_text('\n'.join(o))
    total = len(bitmap) + 12 * len(glyphs) + 12 * len(runs)
    print('%s: %d glyphs, bitmap %d B, tables %d B, total %d B, ascender %d, descender %d' %
          (name, len(cps), len(bitmap), 12 * len(glyphs) + 12 * len(runs), total, asc, desc))
    return total


if __name__ == '__main__':
    OUT.mkdir(parents=True, exist_ok=True)
    print('flash total', sum(emit(px, cps) for px, cps in SIZES.items()), 'B')
