#!/usr/bin/env python3
"""Write the icon headers of tenor/cross from the shapes in hinh.py, drawn by net.py.

    python3 scripts/icons/sinh.py            # rewrite the headers
    python3 scripts/icons/sinh.py --check    # exit 1 when a header on disk differs from what this makes

Format of freeink::Icon (see freeink-sdk/libs/assets/Icons/include/Icon.h): 1 bit, every row padded
to a multiple of 8 bits, high bit first, bit 0 = ink. The last field is the optical centre row, the
mean row of the ink. The arrays are `inline constexpr`: one copy in the image however many .cpp
files include the header (a `static const` array is copied into each one that uses it).

Stroke by size: 40 px cards use 3, 32 and 24 px icons use 2 (the weight follows the text beside it).

MoonIcon.h is the one asset in the pre-rotated layout of scripts/convert_icon.py (turned 90 degrees
counter-clockwise, white = 1), drawn by SleepActivity through renderer.drawImage.
"""
import os
import sys

from net import G
import hinh

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, 'src', 'components', 'icons')
MOON = os.path.join(ROOT, 'src', 'images', 'MoonIcon.h')

# (file, size, stroke, [(c name, shape in hinh.py) or (c name, shape, own stroke)])
# The tab icons come twice: stroke 3, drawn grey on the bar, and stroke 4 (`_bold`), the selected tab's.
SETS = [
    ('tenorHomeTabIcons.h', 40, 3, [
        ('tenor_home_recent', 'gan_day'), ('tenor_home_folder', 'thu_muc_hop'),
        ('tenor_home_stats', 'thong_ke'), ('tenor_home_settings', 'cai_dat'),
        ('tenor_home_favorites', 'yeu_tim'),
        ('tenor_home_recent_bold', 'gan_day', 4), ('tenor_home_folder_bold', 'thu_muc_hop', 4),
        ('tenor_home_stats_bold', 'thong_ke', 4), ('tenor_home_settings_bold', 'cai_dat', 4),
        ('tenor_home_favorites_bold', 'yeu_tim', 4)]),
    ('tenorReaderTabIcons.h', 40, 3, [
        ('tenor_reader_position', 'vi_tri'), ('tenor_reader_reading', 'doc'),
        ('tenor_reader_tools', 'cong_cu'),
        ('tenor_reader_position_bold', 'vi_tri', 4), ('tenor_reader_reading_bold', 'doc', 4),
        ('tenor_reader_tools_bold', 'cong_cu', 4)]),
    ('tenorRowIcons.h', 32, 2, [
        ('folder', 'thu_muc_hop'), ('file_text', 'tep_chu'), ('image', 'tep_anh'), ('book', 'tep_sach'),
        ('file', 'tep'), ('wifi', 'wifi'), ('library', 'thu_vien'), ('radio_tower', 'diem_phat'),
        ('bookmark', 'vi_tri')]),
    ('tenorTransferIcons.h', 24, 2, [('download', 'tai_xuong'), ('upload', 'tai_len')]),
    # The status strip at the top of the touch shell: shown only while the radio is on.
    ('tenorStatusIcons.h', 18, 2, [('status_wifi', 'wifi'), ('status_bluetooth', 'bluetooth'),
                                   ('status_bluetooth_lost', 'bluetooth_hong')]),
    # The mark of the value in use at the end of a row in a list of choices (touch shell).
    ('tenorRowMarks.h', 24, 2, [('row_chosen', 'chon')]),
    ('search32.h', 32, 2, [('search', 'tim')]),
    ('readerToolbarIcons.h', 24, 2, [
        ('reader_contents', 'muc_luc'), ('reader_text', 'chu'), ('reader_more', 'them'),
        ('reader_back', 'lui'), ('reader_next', 'toi'), ('reader_tick', 'dau_tich'),
        ('reader_align_justify', 'can_deu'), ('reader_align_left', 'can_trai'), ('reader_align_center', 'can_giua'),
        ('reader_align_right', 'can_phai'), ('reader_align_book', 'can_sach'),
        ('reader_spacing_1', 'gian_1'), ('reader_spacing_2', 'gian_2'), ('reader_spacing_3', 'gian_3'),
        ('reader_spacing_4', 'gian_4'), ('reader_spacing_5', 'gian_5'),
        ('reader_dropcap_off', 'hoa_tat'), ('reader_dropcap_default', 'hoa_vua'), ('reader_dropcap_large', 'hoa_lon')]),
]


def draw(shape, n, w):
    g = G(n, w)
    hinh.H[shape][1](g)
    return g.img()


def pack(im):
    """Rows of bytes, high bit first, 1 = leave the pixel, 0 = ink; plus the optical centre row."""
    n = im.width
    px = im.load()
    data, sum_y, count = [], 0, 0
    for y in range(im.height):
        for xb in range(0, n, 8):
            byte = 0
            for b in range(8):
                x = xb + b
                white = 1
                if x < n and px[x, y] == 0:
                    white = 0
                    sum_y += y
                    count += 1
                byte |= white << (7 - b)
            data.append(byte)
    return data, (round(sum_y / count) if count else n // 2)


def wrap(values, per_line, close):
    lines = []
    for i in range(0, len(values), per_line):
        lines.append('    ' + ', '.join(f'0x{b:02X}' for b in values[i:i + per_line]))
    return ',\n'.join(lines) + close


def header(name, n, w, items):
    out = ['#pragma once', '', '#include "Icon.h"', '',
           '// Generated by scripts/icons/sinh.py from scripts/icons/hinh.py. Do not edit.',
           f'// Size: {n}px, stroke {w} unless the name ends in _bold (stroke 4). Icons: {len(items)}.', '']
    for cname, shape, *own in items:
        data, cy = pack(draw(shape, n, own[0] if own else w))
        arr = f'icon_{cname}_{n}_bits'
        out.append(f'// {cname}  ({shape})')
        out.append(f'inline constexpr uint8_t {arr}[] = {{')
        out.append(wrap(data, 19, '};'))
        out.append(f'inline constexpr freeink::Icon icon_{cname}_{n} = {{{n}, {n}, {cy}, {arr}}};')
        out.append('')
    return '\n'.join(out).rstrip('\n') + '\n'


def moon():
    im = draw('trang_khuyet', 48, 3).rotate(90, expand=True)
    data, _ = pack(im)
    return ('#pragma once\n#include <cstdint>\n\n// Image dimensions: 48x48\n#define MOONICON_WIDTH 48\n'
            '#define MOONICON_HEIGHT 48\n\nstatic const uint8_t MoonIcon[] = {\n' + wrap(data, 18, '};') + '\n')


def outputs():
    res = {os.path.join(OUT, f): header(f, n, w, items) for f, n, w, items in SETS}
    res[MOON] = moon()
    return res


def main():
    check = '--check' in sys.argv[1:]
    bad = 0
    for path, text in outputs().items():
        have = open(path).read() if os.path.exists(path) else None
        if check:
            if have != text:
                print('differs:', os.path.relpath(path, ROOT))
                bad += 1
        else:
            open(path, 'w').write(text)
            print('wrote', os.path.relpath(path, ROOT))
    sys.exit(1 if bad else 0)


if __name__ == '__main__':
    main()
