#!/usr/bin/env python3
"""Pool identical built-in font metadata while keeping descriptors and glyphs intact."""

import argparse
from collections import defaultdict
import hashlib
import json
from pathlib import Path
import re
import sys

sys.dont_write_bytecode = True
from font_header_tools import ARRAY, SHARED_HEADER, expand_header


METADATA = (
    'Intervals', 'KernLeftCodepoints', 'KernLeftClassIds', 'KernRightCodepoints',
    'KernRightClassIds', 'KernRowOffsets', 'KernSparseCols', 'KernSparseValues', 'LigaturePairs',
)
FIELDS = {'EpdUnicodeInterval': 3, 'EpdLigaturePair': 2, 'uint16_t': 1, 'uint8_t': 1, 'int8_t': 1}
NUMBER = re.compile(r'-?(?:0[xX][0-9a-fA-F]+|\d+)')


def identity(match):
    kind, name, count, body = match.groups()
    if kind not in FIELDS:
        raise ValueError(f'Unsupported font metadata type: {kind}')
    body = re.sub(r'/\*.*?\*/|//[^\n]*', '', body, flags=re.S)
    if re.sub(r'[\s,{}]', '', NUMBER.sub('', body)):
        raise ValueError(f'Non-numeric font metadata initializer: {name}')
    values = tuple(int(v, 16) if 'x' in v.lower() else int(v, 10) for v in NUMBER.findall(body))
    if not values or len(values) % FIELDS[kind] or (count and int(count) != len(values) // FIELDS[kind]):
        raise ValueError(f'Invalid font metadata element count: {name}')
    return kind, values


def outputs(directory):
    headers = {}
    groups = defaultdict(list)
    for path in sorted(directory.glob('*.h')):
        if not re.search(r'static const EpdFontData\s+\w+\s*=', path.read_text(encoding='utf-8')):
            continue
        text = expand_header(path)
        headers[path] = text
        for match in ARRAY.finditer(text):
            if match.group(2).endswith(METADATA):
                groups[identity(match)].append((path, match))

    replacements = {}
    shared = {}
    for key, members in groups.items():
        if len(members) < 2:
            continue
        symbol = 'data_' + hashlib.sha256(json.dumps(key, separators=(',', ':')).encode()).hexdigest()[:16]
        if symbol in shared:
            raise ValueError(f'Font metadata symbol collision: {symbol}')
        kind, _, _, body = members[0][1].groups()
        shared[symbol] = f'inline constexpr {kind} {symbol}[] = {{{body}}};\n'
        for path, match in members:
            replacements[(path, match.group(2))] = symbol

    result = {}
    for path, text in headers.items():
        pooled = False

        def replace(match):
            nonlocal pooled
            symbol = replacements.get((path, match.group(2)))
            if symbol is None:
                return match.group(0)
            pooled = True
            return f'static constexpr auto& {match.group(2)} = builtin_font_metadata::{symbol};'

        text = ARRAY.sub(replace, text)
        if pooled:
            text = text.replace('#pragma once\n', '#pragma once\n#include "builtin_font_metadata.h"\n', 1)
            if '#include "builtin_font_metadata.h"' not in text:
                raise ValueError(f'Missing pragma once in font header: {path}')
        result[path] = text
    result[directory / SHARED_HEADER] = (
        '// Generated by scripts/deduplicate_font_metadata.py.\n#pragma once\n'
        '#include "EpdFontData.h"\n\nnamespace builtin_font_metadata {\n\n'
        + '\n'.join(shared[name] for name in sorted(shared))
        + '\n}  // namespace builtin_font_metadata\n'
    )
    return result, len(headers), len(shared)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('directory', type=Path)
    parser.add_argument('--check', action='store_true', help='Fail if pooling would change any header')
    args = parser.parse_args()
    result, fonts, tables = outputs(args.directory)
    if not fonts:
        parser.error('No built-in font descriptors found')
    changed = [p for p, text in result.items() if not p.exists() or p.read_text(encoding='utf-8') != text]
    if args.check:
        if changed:
            print('Font metadata requires regeneration: ' + ', '.join(p.name for p in changed), file=sys.stderr)
            return 1
    else:
        for path in changed:
            path.write_text(result[path], encoding='utf-8')
    print(f'{fonts} fonts; {tables} shared metadata tables; {len(changed)} changed headers')
    return 0


if __name__ == '__main__':
    sys.exit(main())
