"""Generate src/components/QuoteMarkGlyph.h: the opening double quotation mark (U+201C)
the Quotes detail screen draws above the quoted text (mockup D2). Reproducible: same
font file in, same header out, every run.

Source: lib/EpdFont/builtinFonts/source/NotoSerif/NotoSerif-Bold.ttf, already shipped in
the flash font set and licensed OFL (see the OFL.txt next to it), so this glyph costs no
extra font weight.

Usage: python3 scripts/gen_quote_mark.py
"""
import os

import numpy as np
from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT_PATH = os.path.join(ROOT, 'lib/EpdFont/builtinFonts/source/NotoSerif/NotoSerif-Bold.ttf')
OUT_PATH = os.path.join(ROOT, 'src/components/QuoteMarkGlyph.h')

GLYPH = '“'  # LEFT DOUBLE QUOTATION MARK
POINT_SIZE = 44
# Every phac-thao mockup, and the machine itself, sizes a font in pixels as pt * 150/72
# (150 DPI). Screens.py documents the same constant.
EM_PX = round(POINT_SIZE * 150 / 72)
THRESHOLD = 128  # matches scripts/convert_icon.py, the tree's other drawImage asset generator


def render_glyph():
    font = ImageFont.truetype(FONT_PATH, EM_PX)
    canvas = Image.new('L', (EM_PX * 2, EM_PX * 2), 255)
    draw = ImageDraw.Draw(canvas)
    draw.text((EM_PX // 2, EM_PX // 2), GLYPH, font=font, fill=0)
    ink_rows, ink_cols = np.where(np.array(canvas) < THRESHOLD)
    if ink_rows.size == 0:
        raise RuntimeError('glyph render is blank, font or codepoint changed?')
    bbox = (int(ink_cols.min()), int(ink_rows.min()), int(ink_cols.max()) + 1, int(ink_rows.max()) + 1)
    return canvas.crop(bbox)


def pack_1bpp(img):
    """1bpp, MSB-first, 1=white 0=black, row stride ceil(width/8) bytes: the format
    FreeInkDisplay::blitImage() (freeink-sdk/libs/display/FreeInkDisplay/src/FreeInkDisplay.cpp)
    reads, reached through GfxRenderer::drawImage() (lib/GfxRenderer/GfxRenderer.h)."""
    width, height = img.size
    row_bytes = (width + 7) // 8
    data = bytearray(row_bytes * height)
    px = img.load()
    for y in range(height):
        for x in range(width):
            if px[x, y] >= THRESHOLD:
                data[y * row_bytes + (x >> 3)] |= 0x80 >> (x & 7)
    return bytes(data)


def main():
    glyph = render_glyph()
    logical_width, logical_height = glyph.size

    # GfxRenderer::drawImage() only rotates the image's placement corner for Portrait
    # orientation (the "TODO: Rotate bits" note beside its call in
    # lib/GfxRenderer/GfxRenderer.cpp); it never rotates the pixel data itself. Every other
    # drawImage asset in this tree (src/images/MoonIcon.h, built by scripts/convert_icon.py)
    # compensates by pre-rotating the source art 90 degrees before packing, so this glyph
    # follows the same convention.
    rotated = glyph.rotate(90, expand=True)
    draw_width, draw_height = rotated.size
    data = pack_1bpp(rotated)
    if len(data) > 1024:
        raise RuntimeError(f'glyph packs to {len(data)} bytes, over the 1 KB budget')

    lines = []
    for i in range(0, len(data), 16):
        lines.append('    ' + ', '.join(f'0x{b:02X}' for b in data[i:i + 16]) + ',')
    body = '\n'.join(lines)

    header = f"""#pragma once
#include <cstdint>

// The opening double quotation mark the Quotes detail screen draws above the quoted
// text (mockup D2). Generated by scripts/gen_quote_mark.py from
// lib/EpdFont/builtinFonts/source/NotoSerif/NotoSerif-Bold.ttf (OFL, already shipped),
// glyph U+201C at {POINT_SIZE}pt * 150/72 = {EM_PX}px, trimmed to its ink. Regenerate
// with that script instead of hand-editing the bytes below.
//
// QUOTE_MARK_GLYPH_WIDTH/HEIGHT are the glyph's own size, reading upright on the panel
// ({logical_width}x{logical_height}px): use these for layout math (QuoteDetailLayout).
//
// The bytes below are rotated 90 degrees from that reading orientation before packing.
// GfxRenderer::drawImage() (lib/GfxRenderer/GfxRenderer.h) only rotates an image's
// placement corner for Portrait orientation, never its pixel data (see the "TODO:
// Rotate bits" note beside its call in lib/GfxRenderer/GfxRenderer.cpp), so an asset
// has to arrive pre-rotated to read upright once blitted. src/images/MoonIcon.h (built
// by scripts/convert_icon.py) follows the same convention; this header matches it.
// QUOTE_MARK_DRAW_WIDTH/HEIGHT are the rotated, packed size: pass them, not the
// GLYPH_WIDTH/HEIGHT above, as the width/height arguments of the call below.
//
//   renderer.drawImage(kQuoteMarkGlyphBitmap, x, y, QUOTE_MARK_DRAW_WIDTH, QUOTE_MARK_DRAW_HEIGHT);
//
// Format: 1bpp, MSB-first, row stride ceil(width/8) bytes, bit 1 = white, bit 0 = ink.
// That is what FreeInkDisplay::blitImage() (freeink-sdk/libs/display/FreeInkDisplay/src/
// FreeInkDisplay.cpp) reads on the other end of drawImage(), and the same convention
// src/images/MoonIcon.h uses.
constexpr int16_t QUOTE_MARK_GLYPH_WIDTH = {logical_width};
constexpr int16_t QUOTE_MARK_GLYPH_HEIGHT = {logical_height};
constexpr int16_t QUOTE_MARK_DRAW_WIDTH = {draw_width};
constexpr int16_t QUOTE_MARK_DRAW_HEIGHT = {draw_height};

static const uint8_t kQuoteMarkGlyphBitmap[] = {{
{body}
}};
"""
    with open(OUT_PATH, 'w') as f:
        f.write(header)
    print(f'Wrote {OUT_PATH}: glyph {logical_width}x{logical_height}px, packed {len(data)} bytes '
          f'(drawImage size {draw_width}x{draw_height})')


if __name__ == '__main__':
    main()
