#!/usr/bin/env python3
"""Regenerates lib/GfxRenderer/InlineSymbolBitmaps.h from the 1-bit reference
PNGs in lib/GfxRenderer/symbol-sources/. The Back-arrow and Select-tick symbols
are drawn as exact bitmaps, not procedurally, so this script is the only place
their pixels come from.

Switching to another drawn variant is a one-line edit below
(ARROW_VARIANT / TICK_VARIANT) followed by a rerun; only the chosen variant's
pixels are embedded in the generated header, the others are not compiled in.

Usage: python3 scripts/gen_back_arrow.py
"""
import pathlib

REPO = pathlib.Path(__file__).resolve().parents[1]
SOURCE_DIR = REPO / 'lib/GfxRenderer/symbol-sources'
OUTPUT = REPO / 'lib/GfxRenderer/InlineSymbolBitmaps.h'

ARROW_VARIANT = 'B'  # chosen 23/09/2026
TICK_VARIANT = 'T2'  # chosen 23/09/2026


def read_bitmap(path):
    """Reads a 1-bit (black/white) PNG without needing Pillow, so this script
    has no dependency beyond the standard library."""
    import struct
    import zlib
    data = path.read_bytes()
    assert data[:8] == b'\x89PNG\r\n\x1a\n', path
    pos = 8
    width = height = bit_depth = color_type = None
    idat = b''
    while pos < len(data):
        length = struct.unpack('>I', data[pos:pos + 4])[0]
        chunk_type = data[pos + 4:pos + 8]
        chunk = data[pos + 8:pos + 8 + length]
        if chunk_type == b'IHDR':
            width, height, bit_depth, color_type = struct.unpack('>IIBB', chunk[:10])
        elif chunk_type == b'IDAT':
            idat += chunk
        elif chunk_type == b'IEND':
            break
        pos += 12 + length
    raw = zlib.decompress(idat)
    # Grayscale (color_type 0) or grayscale+alpha (4), 8 bits/channel: the
    # only two encodings the reference export produced for these glyphs.
    channels = {0: 1, 4: 2}[color_type]
    stride = 1 + width * channels
    rows = []
    prev = bytes(width * channels)
    for y in range(height):
        start = y * stride
        filter_type = raw[start]
        line = bytearray(raw[start + 1:start + stride])
        if filter_type == 1:  # Sub
            for i in range(channels, len(line)):
                line[i] = (line[i] + line[i - channels]) & 0xff
        elif filter_type == 2:  # Up
            for i in range(len(line)):
                line[i] = (line[i] + prev[i]) & 0xff
        elif filter_type == 3:  # Average
            for i in range(len(line)):
                a = line[i - channels] if i >= channels else 0
                b = prev[i]
                line[i] = (line[i] + (a + b) // 2) & 0xff
        elif filter_type == 4:  # Paeth
            for i in range(len(line)):
                a = line[i - channels] if i >= channels else 0
                b = prev[i]
                c = prev[i - channels] if i >= channels else 0
                p = a + b - c
                pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
                pred = a if pa <= pb and pa <= pc else (b if pb <= pc else c)
                line[i] = (line[i] + pred) & 0xff
        elif filter_type != 0:
            raise ValueError(f'unsupported PNG filter {filter_type}')
        prev = bytes(line)
        rows.append(bytes(line))
    bits = []
    for y in range(height):
        row = []
        for x in range(width):
            sample = rows[y][x * channels]
            row.append(sample < 128)  # black (ink) => True
        bits.append(row)
    return width, height, bits


def emit_glyph(name, width, height, bits):
    lines = [f'constexpr uint32_t k{name}Rows[] = {{']
    for row in bits:
        value = 0
        for x, on in enumerate(row):
            if on:
                value |= 1 << (width - 1 - x)
        lines.append(f'    0x{value:08X},')
    lines.append('};')
    lines.append(f'constexpr Glyph k{name}{{k{name}Rows, {width}, {height}}};')
    return '\n'.join(lines)


def main():
    arrow14 = read_bitmap(SOURCE_DIR / f'{ARROW_VARIANT}-net14.png')
    arrow18 = read_bitmap(SOURCE_DIR / f'{ARROW_VARIANT}-net18.png')
    tick14 = read_bitmap(SOURCE_DIR / f'{TICK_VARIANT}-tick-net14.png')
    tick18 = read_bitmap(SOURCE_DIR / f'{TICK_VARIANT}-tick-net18.png')

    parts = [
        '#pragma once',
        '#include <cstdint>',
        '// Generated by scripts/gen_back_arrow.py from the reference PNGs',
        f'// (variant {ARROW_VARIANT} for the return arrow, {TICK_VARIANT} for the tick).',
        '// Do not hand-edit; rerun the script to change the variant or refresh pixels.',
        'namespace inlineSymbolBitmaps {',
        'struct Glyph {',
        '  const uint32_t* rows;  // one entry per row, bit (width-1-x) set means ink',
        '  int width;',
        '  int height;',
        '};',
        emit_glyph('BackNet14', *arrow14[:2], arrow14[2]),
        emit_glyph('BackNet18', *arrow18[:2], arrow18[2]),
        emit_glyph('SelectNet14', *tick14[:2], tick14[2]),
        emit_glyph('SelectNet18', *tick18[:2], tick18[2]),
        '}  // namespace inlineSymbolBitmaps',
        '',
    ]
    OUTPUT.write_text('\n'.join(parts))
    print(f'Wrote {OUTPUT} ({OUTPUT.stat().st_size} bytes)')
    for label, (w, h, _) in (('arrow14', arrow14), ('arrow18', arrow18), ('tick14', tick14), ('tick18', tick18)):
        print(f'  {label}: {w}x{h}')


if __name__ == '__main__':
    main()
