#!/usr/bin/env python3
"""Build the menu thumbnail from the exact bundled sleep-screen planes.

Area reduction preserves tone before encoding for the one-bit menu framebuffer.
No full-screen decompression, SD read or allocation is required on the device.
"""
import hashlib
import re
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'src/components/X3BrandAssets.h'
DEST = ROOT / 'src/components/X3SleepCover.h'
W, H, TW, TH = 528, 792, 120, 180
BAYER = ((0, 8, 2, 10), (12, 4, 14, 6), (3, 11, 1, 9), (15, 7, 13, 5))

def build():
    source = SOURCE.read_text()
    planes = []
    for name in ('SLEEP_LSB', 'SLEEP_MSB'):
        block = re.search(r'uint8_t ' + name + r'\[\] = \{(.*?)\};', source, re.S).group(1)
        packed = bytes(int(v, 16) for v in re.findall(r'0x([0-9a-fA-F]{2})', block))
        plane = zlib.decompress(packed)
        assert len(plane) == W * H // 8
        planes.append(plane)
    def level(x, y):
        bit = (W - 1 - x) * H + y
        return sum(((plane[bit // 8] >> (7 - bit % 8)) & 1) << i for i, plane in enumerate(planes))
    pixels = []
    for y in range(TH):
        for x in range(TW):
            total = 0
            for sy in range(y * H // TH, ((y + 1) * H + TH - 1) // TH):
                wy = min((sy + 1) * TH, (y + 1) * H) - max(sy * TH, y * H)
                for sx in range(x * W // TW, ((x + 1) * W + TW - 1) // TW):
                    wx = min((sx + 1) * TW, (x + 1) * W) - max(sx * TW, x * W)
                    total += level(sx, sy) * wx * wy
            # Bit one is white; midpoint thresholds keep black and white exact.
            pixels.append(32 * total > (2 * BAYER[y % 4][x % 4] + 1) * 3 * W * H)
    packed = bytes(sum(int(pixels[i+j]) << (7-j) for j in range(8)) for i in range(0, len(pixels), 8))
    assert len(packed) == 2700
    digest = hashlib.sha256(b''.join(planes)).hexdigest()
    lines = ['// Generated by scripts/pack_sleep_cover.py from the bundled sleep artwork.',
             '// Source planes SHA256: ' + digest, '#pragma once', '#include <cstdint>',
             'namespace sleepcover {', f'inline constexpr int WIDTH = {TW}, HEIGHT = {TH};',
             'inline constexpr uint8_t PIXELS[] = {']
    lines += ['  ' + ', '.join(f'0x{v:02x}' for v in packed[i:i+20]) + ',' for i in range(0, len(packed), 20)]
    lines += ['};', 'static_assert(sizeof(PIXELS) == WIDTH * HEIGHT / 8);', '}  // namespace sleepcover']
    DEST.write_text('\n'.join(lines) + '\n')
    print(f'{len(packed)} bytes; source {digest}')

if __name__ == '__main__':
    build()
