#!/usr/bin/env python3
"""Pack approved four-level X3 BMPs as compressed native display planes.

The source already contains its Bayer pattern. Packing preserves every level
and rotates coordinates only, without resampling or a second dither.
"""
import argparse
import hashlib
import zlib
from pathlib import Path

from PIL import Image

WIDTH, HEIGHT = 528, 792
SOURCES = (
    ("BOOT", "260915_tenor_branding_xteink-x3-cross-khoi-dong.bmp"),
    ("SLEEP", "260915_tenor_branding_xteink-x3-cross-muc-dang.bmp"),
)


def build(source_dir: Path, output: Path) -> None:
    lines = [
        "// Generated by scripts/pack_x3_brand.py. Do not edit pixel data by hand.",
        "#pragma once", "#include <cstddef>", "#include <cstdint>",
        "namespace x3brand {",
        f"inline constexpr int WIDTH = {WIDTH}, HEIGHT = {HEIGHT};",
        "inline constexpr size_t PLANE_BYTES = WIDTH * HEIGHT / 8;",
    ]
    for name, filename in SOURCES:
        path = source_dir / filename
        im = Image.open(path).convert("RGB")
        if im.size != (WIDTH, HEIGHT):
            raise ValueError(f"Unexpected image dimensions: {path}")
        pixels = im.tobytes()
        if any(pixels[i] != pixels[i + 1] or pixels[i] != pixels[i + 2]
               or pixels[i] not in (0, 85, 170, 255) for i in range(0, len(pixels), 3)):
            raise ValueError(f"Image must already be four-level grayscale: {path}")
        if name == "BOOT" and any(value != 255 for value in pixels[750 * WIDTH * 3:]):
            raise ValueError("Version area at y >= 750 must remain white")
        # Portrait (x, y) becomes native (y, 527-x), with 792 pixels per row.
        native = im.transpose(Image.Transpose.ROTATE_90).convert("L").tobytes()
        levels = [value // 85 for value in native]
        lines.append(f"// Source: {filename} SHA256 {hashlib.sha256(path.read_bytes()).hexdigest()}")
        for bit, label in ((0, "LSB"), (1, "MSB")):
            plane = bytes(sum(((levels[i + j] >> bit) & 1) << (7 - j) for j in range(8))
                          for i in range(0, len(levels), 8))
            packed = zlib.compress(plane, 9)
            if zlib.decompress(packed) != plane:
                raise RuntimeError("Compression round trip failed")
            lines.append(f"inline constexpr uint8_t {name}_{label}[] = {{")
            lines.extend("  " + ", ".join(f"0x{v:02x}" for v in packed[i:i + 20]) + ","
                         for i in range(0, len(packed), 20))
            lines.extend(("};", f"inline constexpr uint32_t {name}_{label}_CRC = 0x{zlib.crc32(plane):08x};"))
            print(name, label, len(packed), "bytes", f"CRC {zlib.crc32(plane):08x}")
    lines.append("}  // namespace x3brand")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-dir", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    build(args.source_dir, args.output)
