#!/usr/bin/env python3
"""Encode the fallback sleep art: python scripts/sinh_man_ngu.py > src/components/ManNguTenor.h.

The fallback is the frame the X3 shows when it has no absolute gray planes (the UC8253 X3). It is
the tenor/cross sleep picture itself, taken from the gray sleep planes in X3BrandAssets.h and
folded to black and white by the rule SleepGrayPlanes::show uses at sleep on the UC8279 X3, so
both panels show the same picture. It is laid out as the portrait framebuffer and zlib wrapped;
the firmware inflates it straight into the framebuffer.

The deflate stream comes from 7-Zip (7zz, many passes), about 280 bytes smaller than zlib's best
on this frame; the stream is standard deflate, which the firmware's inflater reads as any other.
"""
import re
import subprocess
import sys
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'src/components/X3BrandAssets.h'
PLANE_BYTES = 528 * 792 // 8
ROW_BYTES = 792 // 8  # the panel is landscape: one framebuffer row is one column of the picture
# SleepGrayPlanes.cpp, one mask per row: a set bit turns the pixel white.
DARK = (0xAA, 0x00, 0xAA, 0x00)
LIGHT = (0xFF, 0x55, 0xFF, 0x55)


def plane(source: str, name: str) -> bytes:
    block = re.search(r'uint8_t ' + name + r'\[\] = \{(.*?)\};', source, re.S).group(1)
    data = zlib.decompress(bytes(int(v, 16) for v in re.findall(r'0x([0-9a-fA-F]{2})', block)))
    assert len(data) == PLANE_BYTES
    return data


def deflate(data: bytes) -> bytes:
    gz = subprocess.run(['7zz', 'a', '-tgzip', '-mx9', '-mpass=15', '-mfb=258', '-si', '-so', 'frame'],
                        input=data, capture_output=True, check=True).stdout
    # A gzip member with no optional fields: 10 bytes of header, 8 of trailer.
    if gz[:4] != b'\x1f\x8b\x08\x00':
        sys.exit('7zz wrote an unexpected gzip header')
    raw = gz[10:-8]
    packed = b'\x78\xda' + raw + zlib.adler32(data).to_bytes(4, 'big')
    if zlib.decompress(packed) != data:
        sys.exit('packed frame does not inflate back to the frame')
    return packed


def main() -> None:
    source = SOURCE.read_text()
    lsb, msb = plane(source, 'SLEEP_LSB'), plane(source, 'SLEEP_MSB')
    # Absolute planes: LSB white on levels 1 and 3, MSB white on 2 and 3.
    frame = bytes((m & (l | LIGHT[(i // ROW_BYTES) & 3])) | (l & DARK[(i // ROW_BYTES) & 3])
                  for i, (l, m) in enumerate(zip(lsb, msb)))
    packed = deflate(frame)

    out = sys.stdout
    out.write('// Generated by scripts/sinh_man_ngu.py. Do not edit by hand.\n')
    out.write('//\n')
    out.write('// Fallback Tenor sleep screen for the X3 without absolute gray planes (the UC8253 X3): the\n')
    out.write('// tenor/cross sleep picture folded to black and white as the UC8279 X3 folds it at sleep,\n')
    out.write('// laid out as the portrait framebuffer, zlib wrapped.\n')
    out.write(f'// Raw {len(frame)} bytes; packed {len(packed)} bytes.\n')
    out.write('#pragma once\n\n#include <cstdint>\n\nnamespace mannogu {\n\n')
    out.write('inline constexpr uint8_t KHUNG[] = {\n')
    for i in range(0, len(packed), 16):
        out.write('    ' + ' '.join(f'0x{v:02x},' for v in packed[i:i + 16]) + '\n')
    out.write('};\n\n')
    out.write('}  // namespace mannogu\n')


if __name__ == '__main__':
    main()
