#pragma once
#include <cstdint>
// Generated by scripts/gen_back_arrow.py from the reference PNGs
// (variant B for the return arrow, T2 for the tick).
// Do not hand-edit; rerun the script to change the variant or refresh pixels.
namespace inlineSymbolBitmaps {
struct Glyph {
  const uint32_t* rows;  // one entry per row, bit (width-1-x) set means ink
  int width;
  int height;
};
constexpr uint32_t kBackNet14Rows[] = {
    0x00060000,
    0x000F0000,
    0x001F0000,
    0x003E0000,
    0x007C0000,
    0x00FFFFF8,
    0x00FFFFFE,
    0x00FFFFFE,
    0x007C000F,
    0x003C0007,
    0x001E0007,
    0x000F000F,
    0x000703FF,
    0x000007FE,
    0x000003FC,
};
constexpr Glyph kBackNet14{kBackNet14Rows, 24, 15};
constexpr uint32_t kBackNet18Rows[] = {
    0x00E00000,
    0x01E00000,
    0x03E00000,
    0x07E00000,
    0x0FC00000,
    0x1F800000,
    0x3F000060,
    0x7FFFFFF8,
    0x7FFFFFFC,
    0x7FFFFFFE,
    0x3FFFFFFF,
    0x1F80000F,
    0x0FC0000F,
    0x07E0000F,
    0x03E0001F,
    0x01E01FFF,
    0x00E01FFE,
    0x00001FFC,
    0x00001FF8,
};
constexpr Glyph kBackNet18{kBackNet18Rows, 31, 19};
constexpr uint32_t kSelectNet14Rows[] = {
    0x00000007,
    0x0000000F,
    0x0000000F,
    0x0000001E,
    0x0000003C,
    0x00000078,
    0x000000F0,
    0x000E01E0,
    0x000F03C0,
    0x00078780,
    0x0003CF00,
    0x0001FE00,
    0x0000FC00,
    0x00007800,
    0x00003000,
};
constexpr Glyph kSelectNet14{kSelectNet14Rows, 20, 15};
constexpr uint32_t kSelectNet18Rows[] = {
    0x00000006,
    0x0000000F,
    0x0000001F,
    0x0000003F,
    0x0000007C,
    0x000000F8,
    0x000001F0,
    0x000003F0,
    0x018007E0,
    0x03C00FC0,
    0x03E01F80,
    0x03F03F00,
    0x01F87E00,
    0x00FCFC00,
    0x003FF800,
    0x001FF000,
    0x000FE000,
    0x0007C000,
    0x00038000,
};
constexpr Glyph kSelectNet18{kSelectNet18Rows, 26, 19};
}  // namespace inlineSymbolBitmaps
