int failures=0,tests=0;
void require(bool yes,const char*message){if(!yes)throw std::runtime_error(message);}
void test(const std::string&name,std::function<void()>fn){tests++; RenderLock::busy=false;nowMs=1000;READING_STATS={};activityManager.generation=1;activityManager.pendingAction=ActivityManager::PendingAction::None;activityManager.sleepTransition=false;activityManager.exclusive=false;activityManager.preventSleep=false;gpio={};mappedInputManager={};powerManager={};halTiltSensor={};filetransfer::active=false;freeink::BleKeyboardHost::getInstance()={};freeink::ble::stopped=false;freeink::ble::init=false;freeink::ble::starts=0;freeink::ble::startSuccess=true;SETTINGS.blePageTurnerEnabled=true;
 try{fn();std::cout<<"PASS "<<name<<"\n";}catch(const std::exception&e){failures++;std::cout<<"FAIL "<<name<<": "<<e.what()<<"\n";}RenderLock::busy=false;activityManager.currentActivity.reset();}
template<class T>std::shared_ptr<T>reader(){auto r=std::make_shared<T>();activityManager.currentActivity=r;return r;}
int page(const TxtReaderActivity&r){return r.currentPage;}int page(const XtcReaderActivity&r){return r.currentPage;}int page(const EpubReaderActivity&r){return r.section?r.section->currentPage:-1;}
void last(TxtReaderActivity&r){r.currentPage=3;}void last(XtcReaderActivity&r){r.currentPage=3;}void last(EpubReaderActivity&r){r.section->currentPage=3;r.currentSpineIndex=2;}
template<class T>void formatTests(const std::string&name){
 test(name+" manager action updates page, repaint and stats once",[]{auto r=reader<T>();require(activityManager.pageTurn(true),"mapped action was rejected");r->loop();require(page(*r)==2,"page did not advance once");require(r->requests==1,"changed page has no single repaint");r->updateReadingTime(true);require(READING_STATS.pages==1,"accepted turn missing from stats");r->loop();r->updateReadingTime(true);require(READING_STATS.pages==1&&r->requests==1,"idle retry repeats action/stats/repaint");});
 test(name+" render busy defers one action",[]{auto r=reader<T>();RenderLock::busy=true;require(activityManager.pageTurn(true),"busy reader must enqueue");r->loop();require(page(*r)==1&&r->requests==0&&r->trangDaLat==0,"model changed while renderer owns it");RenderLock::busy=false;r->loop();require(page(*r)==2&&r->requests==1&&r->trangDaLat==1,"deferred action was lost or repeated");r->loop();require(page(*r)==2,"deferred action repeated");});
 test(name+" generation change drops deferred action",[]{auto r=reader<T>();RenderLock::busy=true;activityManager.pageTurn(true);activityManager.generation++;RenderLock::busy=false;r->loop();require(page(*r)==1&&r->requests==0&&r->trangDaLat==0,"stale action reached a new activity generation");});
 test(name+" bounded input burst keeps one pending turn",[]{auto r=reader<T>();RenderLock::busy=true;activityManager.pageTurn(true);activityManager.pageTurn(true);activityManager.pageTurn(false);RenderLock::busy=false;r->loop();require(page(*r)==0&&r->trangDaLat==1&&r->requests==1,"burst accumulated multiple turns instead of latest direction");});
 test(name+" end-of-book forward returns home",[]{auto r=reader<T>();last(*r);activityManager.pageTurn(true);r->loop();require(r->isAtEndOfBook(),"last page failed to enter end screen");nowMs+=250;activityManager.pageTurn(true);r->loop();require(r->goHome==1,"end-of-book forward did not use common handler");require(r->trangDaLat==1,"end action counted as another book page");});
 test(name+" end-of-book previous returns to last page",[]{auto r=reader<T>();last(*r);activityManager.pageTurn(true);r->loop();nowMs+=250;activityManager.pageTurn(false);r->loop();require(!r->isAtEndOfBook(),"previous did not leave end screen");require(r->requests==2,"return from end screen must repaint");require(r->trangDaLat==1,"end-screen return counted as ordinary page");});
 test(name+" end menu owns input",[]{auto r=reader<T>();last(*r);activityManager.pageTurn(true);r->loop();nowMs+=250;r->endOfBookOptionsReady=true;r->endOfBookOptions->menu=true;const int requests=r->requests;const auto turns=r->trangDaLat;activityManager.pageTurn(false);r->loop();require(r->isAtEndOfBook()&&r->trangDaLat==turns&&r->requests==requests,"remote bypassed end menu input ownership");});
 test(name+" closing end menu discards its earlier remote report",[]{auto r=reader<T>();last(*r);activityManager.pageTurn(true);r->loop();nowMs+=250;r->endOfBookOptionsReady=true;r->endOfBookOptions->menu=true;activityManager.pageTurn(false);r->loop();r->onReturnFromEndOfBook();r->endOfBookOptions->menu=false;nowMs+=250;r->loop();require(r->trangDaLat==1,"queued remote report replayed after menu closed");});
 test(name+" pending activity rejects enqueue",[]{auto r=reader<T>();activityManager.pendingAction=ActivityManager::PendingAction::Push;require(!activityManager.pageTurn(true),"transitioning reader accepted remote input");r->loop();require(page(*r)==1,"transitioning reader changed model");});
}
int main(){
 formatTests<TxtReaderActivity>("TXT");formatTests<XtcReaderActivity>("XTC");formatTests<EpubReaderActivity>("EPUB");
 test("EPUB chapter forward holds one nonrecursive lock",[]{auto r=reader<EpubReaderActivity>();r->section->currentPage=3;activityManager.pageTurn(true);r->loop();require(r->currentSpineIndex==1&&!r->section&&r->requests==1&&r->trangDaLat==1,"chapter forward has wrong model/repaint/stats");});
 test("EPUB chapter previous holds one nonrecursive lock",[]{auto r=reader<EpubReaderActivity>();r->section->currentPage=0;r->currentSpineIndex=1;activityManager.pageTurn(false);r->loop();require(r->currentSpineIndex==0&&!r->section&&r->pendingPageJump==65535&&r->requests==1&&r->trangDaLat==1,"chapter previous has wrong model/repaint/stats");});
 test("EPUB 200 ms manual guard defers",[]{auto r=reader<EpubReaderActivity>();r->lastPageTurnTime=900;activityManager.pageTurn(true);r->loop();require(page(*r)==1,"remote bypassed 200 ms guard");nowMs=1100;r->loop();require(page(*r)==2&&r->requests==1&&r->trangDaLat==1,"guard expiry did not drain once");});
 test("EPUB overlay rejects remote action",[]{auto r=reader<EpubReaderActivity>();r->overlay=EpubReaderActivity::Overlay::Toolbar;require(!activityManager.pageTurn(true),"overlay accepted remote action");r->loop();require(page(*r)==1&&r->requests==0,"remote bypassed toolbar");});
 test("EPUB opening overlay drops queued action",[]{auto r=reader<EpubReaderActivity>();RenderLock::busy=true;activityManager.pageTurn(true);r->overlay=EpubReaderActivity::Overlay::WordPicker;RenderLock::busy=false;r->loop();r->overlay=EpubReaderActivity::Overlay::None;nowMs+=250;r->loop();require(page(*r)==1&&r->requests==0,"overlay retained stale deferred action");});

 test("BLE-04 mapped report updates both clocks and displayed page",[]{auto r=reader<TxtReaderActivity>();MainPump p;nowMs=59000;freeink::BleKeyboardHost::getInstance().queue={{1,0}};p.pump();r->loop();require(p.lastActivityTime==59000&&p.lastSleepResetTime==59000,"accepted BLE report did not reset both clocks");require(page(*r)==2&&r->requests==1,"main-to-reader action did not repaint exactly once");});
 test("BLE-04 unmapped and modifier reports leave both clocks",[]{auto r=reader<TxtReaderActivity>();MainPump p;nowMs=59000;freeink::BleKeyboardHost::getInstance().queue={{42,0},{1,1}};p.pump();r->loop();require(p.lastActivityTime==1000&&p.lastSleepResetTime==1000&&page(*r)==1,"unmapped remote input kept reader awake");});
 test("BLE-04 deferred drain resets activity once per new event",[]{auto r=reader<TxtReaderActivity>();MainPump p;nowMs=2000;RenderLock::busy=true;freeink::BleKeyboardHost::getInstance().queue={{1,0}};p.pump();r->loop();require(p.lastSleepResetTime==2000,"queued event failed to reset sleep");for(int i=0;i<10;i++){nowMs+=100;p.pump();r->loop();}require(p.lastSleepResetTime==2000,"deferred turn repeatedly reset inactivity");RenderLock::busy=false;r->loop();require(page(*r)==2&&r->requests==1,"busy report did not render once after release");nowMs=62000;p.pump();require(nowMs-p.lastSleepResetTime>=60000,"idle timeout cannot elapse after final report");});
 test("BLE-04 remote-only reading survives timeout then becomes idle",[]{auto r=reader<TxtReaderActivity>();MainPump p;freeink::BleKeyboardHost::getInstance().connected=true;for(int i=0;i<10;i++){nowMs+=40000;freeink::BleKeyboardHost::getInstance().queue={{i%2?2:1,0}};p.pump();r->loop();require(nowMs-p.lastSleepResetTime<60000,"active remote-only reader reached sleep deadline");}nowMs+=60000;p.pump();require(nowMs-p.lastSleepResetTime==60000,"remote silence failed to reach sleep deadline");});
 for(int button=0;button<4;button++)test("BLE-05 local page release rearms once button "+std::to_string(button),[button]{auto r=reader<TxtReaderActivity>();MainPump p;p.pump();nowMs+=300001;p.pump();require(freeink::ble::idleStopped()&&!freeink::BleKeyboardHost::getInstance().running,"disconnected radio did not idle-off");mappedInputManager.released=true;mappedInputManager.releasedButton=button;nowMs++;p.pump();require(freeink::ble::starts==1&&!freeink::ble::idleStopped()&&freeink::BleKeyboardHost::getInstance().running,"physical page action did not rearm radio");mappedInputManager.released=false;for(int i=0;i<20;i++){nowMs+=100;p.pump();}require(freeink::ble::starts==1,"rearm allocated repeatedly without new intent");});
 test("BLE-05 touch rearms once",[]{auto r=reader<TxtReaderActivity>();MainPump p;p.pump();nowMs+=300001;p.pump();gpio.touch=true;nowMs++;p.pump();require(freeink::ble::starts==1&&!freeink::ble::idleStopped(),"reader touch did not rearm idle radio");});
 test("BLE-05 failed rearm is bounded without allocation retries",[]{auto r=reader<TxtReaderActivity>();MainPump p;p.pump();nowMs+=300001;p.pump();freeink::ble::startSuccess=false;mappedInputManager.released=true;nowMs++;p.pump();mappedInputManager.released=false;for(int i=0;i<20;i++){nowMs+=100;p.pump();}require(freeink::ble::starts==1,"failed reader rearm did not make exactly one attempt");});
 test("BLE-05 connected idle remote remains on",[]{auto r=reader<TxtReaderActivity>();MainPump p;freeink::BleKeyboardHost::getInstance().connected=true;p.pump();nowMs+=600000;p.pump();require(!freeink::ble::idleStopped()&&freeink::BleKeyboardHost::getInstance().running,"connected remote was stopped by idle rule");});

 for(bool previewMode:{false,true}) {
  test(std::string("TXT local tap during render drains once preview=")+(previewMode?"yes":"no"),[previewMode]{auto r=reader<TxtReaderActivity>();r->preview=previewMode;r->statsEnabled=!previewMode;RenderLock::busy=true;r->mappedInput.next=true;r->loop();r->mappedInput.next=false;require(page(*r)==1,"busy local tap mutated renderer-owned model");RenderLock::busy=false;r->loop();require(page(*r)==2&&r->trangDaLat==1&&r->requests>=1,"busy local tap was lost");r->updateReadingTime(true);require(READING_STATS.pages==(previewMode?0u:1u),"preview/local reading stats mismatch");int requests=r->requests;r->loop();require(page(*r)==2&&r->requests==requests,"drained local tap repeated");});
  test(std::string("XTC local tap during render drains once preview=")+(previewMode?"yes":"no"),[previewMode]{auto r=reader<XtcReaderActivity>();r->preview=previewMode;r->statsEnabled=!previewMode;RenderLock::busy=true;r->mappedInput.next=true;r->loop();r->mappedInput.next=false;require(page(*r)==1,"busy local tap mutated renderer-owned model");RenderLock::busy=false;r->loop();require(page(*r)==2&&r->trangDaLat==1&&r->requests>=1,"busy local tap was lost");r->updateReadingTime(true);require(READING_STATS.pages==(previewMode?0u:1u),"preview/local reading stats mismatch");int requests=r->requests;r->loop();require(page(*r)==2&&r->requests==requests,"drained local tap repeated");});
 }
 test("EPUB deferred remote preserves local Back priority",[]{auto r=reader<EpubReaderActivity>();RenderLock::busy=true;activityManager.pageTurn(true);r->mappedInput.back=true;r->loop();require(r->backCalls==1,"remote deferral swallowed Back release");require(page(*r)==1,"Back tick changed page");});
 test("EPUB deferred remote preserves local Confirm priority",[]{auto r=reader<EpubReaderActivity>();RenderLock::busy=true;activityManager.pageTurn(true);r->mappedInput.confirm=true;r->loop();require(r->openedMenus==1,"remote deferral swallowed Confirm release");require(page(*r)==1,"Confirm tick changed page");});
 std::cout<<"RESULT "<<tests-failures<<"/"<<tests<<" passed\n";return failures?1:0;
}
